# Package Overview
PACKAGE_NAME: classification_model

# Data Files
TRAINING_DATA_FILE: train.csv
TESTING_DATA_FILE: test.csv

MODEL_PIPELINE_NAME: gbm_classification_output_v

# Variables
# The variable we are attempting to predict (sale price)
TARGET_FEATURE_NAME: status_group

VARIABLES_TO_KEEP:
  - amount_tsh
  - gps_height
  - construction_year
  - population
  - region
  - basin
  - public_meeting
  - scheme_management
  - permit
  - extraction_type_class
  - management_group
  - payment_type
  - quality_group
  - quantity_group
  - source_type
  - waterpoint_type_group


NUMERICAL_VARIABLES:
  - amount_tsh
  - gps_height
  - construction_year
  - population

YEO_JHONSON_VARIABLES:
  - amount_tsh
  - gps_height
  - population

VARIABLES_TO_GROUP:
  region:
    Dodoma,Singida:
      - Dodoma
      - Singida
    Mara,Tabora,Rukwa,Mtwara,Lindi:
      - Mara
      - Tabora
      - Rukwa
      - Mtwara
      - Lindi
    Manyara,Dar es Salaam,Tanga:
      - Manyara
      - Dar es Salaam
      - Tanga

# Categorical variables (no boolean)
REAL_CATEGORICAL_VARIABLES:
  - region
  - basin
  - scheme_management
  - extraction_type_class
  - management_group
  - payment_type
  - quality_group
  - quantity_group
  - source_type
  - waterpoint_type_group

SEED : 42

ACCEPTABLE_MODEL_DIFFERENCE : 0.05

VARIABLES_THRESHOLD:
  scheme_management: 0.04
  extraction_type_class: 0.06
  management_group: 0.06
  quality_group: 0.08
  source_type: 0.17
  waterpoint_type_group: 0.1
  quantity_group: 0.1

# set train/test split
TEST_SIZE: 0.2

# loss function to be optimized
LOSS_FUNCTION: neg_log_loss

ALLOWED_LOSS_FUNCTIONS:
  - neg_log_loss
